// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pages.proto

package landlady

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf2 "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

type Page struct {
	Url     *URLInfo `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Content []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 处理时间
	HandleAt time.Time `protobuf:"bytes,4,opt,name=handleAt,stdtime" json:"handleAt"`
	// ipfs HASH.
	Hash string `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptorPages, []int{0} }

type URLInfo struct {
	// 原始 URL
	OriginURL string `protobuf:"bytes,1,opt,name=originURL,proto3" json:"originURL,omitempty"`
	// 实际 URL
	RealURL string `protobuf:"bytes,2,opt,name=realURL,proto3" json:"realURL,omitempty"`
	// 去掉query的 URL
	ClearURL string `protobuf:"bytes,3,opt,name=clearURL,proto3" json:"clearURL,omitempty"`
}

func (m *URLInfo) Reset()                    { *m = URLInfo{} }
func (m *URLInfo) String() string            { return proto.CompactTextString(m) }
func (*URLInfo) ProtoMessage()               {}
func (*URLInfo) Descriptor() ([]byte, []int) { return fileDescriptorPages, []int{1} }

type PageList struct {
	Items []*Page `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PageList) Reset()                    { *m = PageList{} }
func (m *PageList) String() string            { return proto.CompactTextString(m) }
func (*PageList) ProtoMessage()               {}
func (*PageList) Descriptor() ([]byte, []int) { return fileDescriptorPages, []int{2} }

func init() {
	proto.RegisterType((*Page)(nil), "landlady.Page")
	proto.RegisterType((*URLInfo)(nil), "landlady.URLInfo")
	proto.RegisterType((*PageList)(nil), "landlady.PageList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pages service

type PagesClient interface {
	Save(ctx context.Context, in *Page, opts ...grpc.CallOption) (*google_protobuf2.Empty, error)
}

type pagesClient struct {
	cc *grpc.ClientConn
}

func NewPagesClient(cc *grpc.ClientConn) PagesClient {
	return &pagesClient{cc}
}

func (c *pagesClient) Save(ctx context.Context, in *Page, opts ...grpc.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc.Invoke(ctx, "/landlady.Pages/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pages service

type PagesServer interface {
	Save(context.Context, *Page) (*google_protobuf2.Empty, error)
}

func RegisterPagesServer(s *grpc.Server, srv PagesServer) {
	s.RegisterService(&_Pages_serviceDesc, srv)
}

func _Pages_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/landlady.Pages/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).Save(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "landlady.Pages",
	HandlerType: (*PagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _Pages_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pages.proto",
}

func (m *Page) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Page) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Url != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPages(dAtA, i, uint64(m.Url.Size()))
		n1, err := m.Url.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Content) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.Content)))
		i += copy(dAtA[i:], m.Content)
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintPages(dAtA, i, uint64(types.SizeOfStdTime(m.HandleAt)))
	n2, err := types.StdTimeMarshalTo(m.HandleAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Hash) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.Hash)))
		i += copy(dAtA[i:], m.Hash)
	}
	return i, nil
}

func (m *URLInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *URLInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OriginURL) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.OriginURL)))
		i += copy(dAtA[i:], m.OriginURL)
	}
	if len(m.RealURL) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.RealURL)))
		i += copy(dAtA[i:], m.RealURL)
	}
	if len(m.ClearURL) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPages(dAtA, i, uint64(len(m.ClearURL)))
		i += copy(dAtA[i:], m.ClearURL)
	}
	return i, nil
}

func (m *PageList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PageList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0xa
			i++
			i = encodeVarintPages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintPages(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Page) Size() (n int) {
	var l int
	_ = l
	if m.Url != nil {
		l = m.Url.Size()
		n += 1 + l + sovPages(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	l = types.SizeOfStdTime(m.HandleAt)
	n += 1 + l + sovPages(uint64(l))
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	return n
}

func (m *URLInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.OriginURL)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	l = len(m.RealURL)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	l = len(m.ClearURL)
	if l > 0 {
		n += 1 + l + sovPages(uint64(l))
	}
	return n
}

func (m *PageList) Size() (n int) {
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovPages(uint64(l))
		}
	}
	return n
}

func sovPages(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPages(x uint64) (n int) {
	return sovPages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Page) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Page: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Page: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Url == nil {
				m.Url = &URLInfo{}
			}
			if err := m.Url.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandleAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.HandleAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *URLInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: URLInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: URLInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RealURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClearURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PageList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PageList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PageList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &Page{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPages
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPages
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPages(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPages = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPages   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pages.proto", fileDescriptorPages) }

var fileDescriptorPages = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbf, 0x6e, 0xea, 0x30,
	0x14, 0xc6, 0x31, 0x04, 0x08, 0xe6, 0xea, 0xea, 0x5e, 0x0f, 0x28, 0xca, 0xbd, 0x0a, 0x51, 0xda,
	0x21, 0x4b, 0x0d, 0xa2, 0x53, 0xb7, 0x16, 0xa9, 0x43, 0x25, 0x86, 0xca, 0x2d, 0x63, 0x07, 0x03,
	0xc6, 0x89, 0x94, 0xc4, 0x51, 0xec, 0x54, 0xe2, 0x2d, 0xfa, 0x2e, 0x7d, 0x09, 0xc6, 0x3e, 0x41,
	0xff, 0xf0, 0x24, 0x95, 0x1d, 0x02, 0x12, 0xdd, 0xce, 0x77, 0xbe, 0x9f, 0x8f, 0xbe, 0x73, 0x0c,
	0xfb, 0x39, 0xe5, 0x4c, 0xe2, 0xbc, 0x10, 0x4a, 0x20, 0x3b, 0xa1, 0xd9, 0x2a, 0xa1, 0xab, 0x8d,
	0xfb, 0x8f, 0x0b, 0xc1, 0x13, 0x36, 0x32, 0xfd, 0x45, 0xb9, 0x1e, 0xb1, 0x34, 0x57, 0x9b, 0x0a,
	0x73, 0x87, 0xa7, 0xa6, 0x8a, 0x53, 0x26, 0x15, 0x4d, 0xf3, 0x3d, 0x70, 0xc1, 0x63, 0x15, 0x95,
	0x0b, 0xbc, 0x14, 0xe9, 0x88, 0x0b, 0x2e, 0x8e, 0xa4, 0x56, 0x46, 0x98, 0xaa, 0xc2, 0x83, 0x57,
	0x00, 0xad, 0x7b, 0xca, 0x19, 0x3a, 0x83, 0xad, 0xb2, 0x48, 0x1c, 0xe0, 0x83, 0xb0, 0x3f, 0xf9,
	0x8b, 0xeb, 0x34, 0x78, 0x4e, 0x66, 0x77, 0xd9, 0x5a, 0x10, 0xed, 0x22, 0x07, 0x76, 0x97, 0x22,
	0x53, 0x2c, 0x53, 0x4e, 0xd3, 0x07, 0xe1, 0x2f, 0x52, 0x4b, 0x34, 0x80, 0x1d, 0xa9, 0xa8, 0x2a,
	0xa5, 0xd3, 0xf2, 0x41, 0xd8, 0x23, 0x7b, 0x85, 0xae, 0xa1, 0x1d, 0xe9, 0x51, 0xec, 0x46, 0x39,
	0x96, 0x99, 0xed, 0xe2, 0x6a, 0x05, 0x5c, 0x07, 0xc3, 0x8f, 0xf5, 0x0a, 0x53, 0x7b, 0xfb, 0x3e,
	0x6c, 0xbc, 0x7c, 0x0c, 0x01, 0x39, 0xbc, 0x42, 0x08, 0x5a, 0x11, 0x95, 0x91, 0xd3, 0x36, 0x73,
	0x4d, 0x1d, 0x3c, 0xc1, 0xee, 0x3e, 0x17, 0xfa, 0x0f, 0x7b, 0xa2, 0x88, 0x79, 0x9c, 0xcd, 0xc9,
	0xcc, 0xa4, 0xef, 0x91, 0x63, 0x43, 0x07, 0x2e, 0x18, 0x4d, 0xb4, 0xd7, 0x34, 0x5e, 0x2d, 0x91,
	0x0b, 0xed, 0x65, 0xc2, 0x68, 0xa1, 0xad, 0x2a, 0xf2, 0x41, 0x07, 0x63, 0x68, 0xeb, 0x9b, 0xcc,
	0x62, 0xa9, 0xd0, 0x39, 0x6c, 0xc7, 0x8a, 0xa5, 0xd2, 0x01, 0x7e, 0x2b, 0xec, 0x4f, 0x7e, 0x1f,
	0x2f, 0xa3, 0x11, 0x52, 0x99, 0x93, 0x2b, 0xd8, 0xd6, 0x52, 0xa2, 0x31, 0xb4, 0x1e, 0xe8, 0x33,
	0x43, 0x27, 0x9c, 0x3b, 0xf8, 0xb1, 0xf5, 0xad, 0xfe, 0xd5, 0xa0, 0x31, 0xfd, 0xb3, 0xfd, 0xf2,
	0x1a, 0xdb, 0x9d, 0x07, 0xde, 0x76, 0x1e, 0xf8, 0xdc, 0x79, 0x60, 0xd1, 0x31, 0xcc, 0xe5, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xcf, 0x01, 0x89, 0x20, 0x02, 0x00, 0x00,
}
